name: build and push rhea-errata

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SECRET }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image and push to github
      run: docker build . --file Containerfile --tag attachment-download:latest
    - name: Tag image
      run: docker image tag attachment-download:latest ghcr.io/backchristoffer/attachment-download:latest
    - name: Push image to github
      run: docker image push ghcr.io/backchristoffer/attachment-download:latest